# Generated by Django 4.2.5 on 2024-05-02 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Regisster',
            new_name='Register',
        ),
    ]
