# Generated by Django 4.2.5 on 2024-05-02 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_rename_category_categorys_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorys',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Sub_Categorys',
            new_name='Sub_Category',
        ),
    ]
